EntregaFinalCoder/myproject/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.CustomLoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('create_story/', views.create_story, name='create_story'),
    path('login_redirect/', views.login_redirect, name='login_redirect'),
    path('edit_story/<int:story_id>/', views.edit_story, name='edit_story'),
    path('delete_story/<int:story_id>/', views.delete_story, name='delete_story'),
    
]

EntregaFinalCoder/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views


# Main URL configuration del proyecto
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('storywriting/', include('storywriting.urls')),
    path('about/', views.about, name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EntregaFinalCoder/myproject/storywriting/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create_story/', views.create_story, name='create_story'),
    path('read_stories/', views.read_stories, name='read_stories'),
    path('join_story/<int:story_id>/', views.join_story, name='join_story'),
    path('browse_stories/', views.browse_stories, name='browse_stories'),
    path('story_detail/<int:story_id>/', views.story_detail, name='story_detail'),
]

EntregaFinalCoder/myproject/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

EntregaFinalCoder/myproject/storywriting/models.py
from django.db import models
from django.contrib.auth.models import User

class Story(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    image = models.ImageField(upload_to='images/', max_length=150)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    genre = models.CharField(max_length=200)

class Contribution(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()

EntregaFinalCoder/myproject/storywriting/forms.py
from django.apps import apps
from django import forms
from .models import Contribution


Story = apps.get_model('storywriting', 'Story')

class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ['title', 'body', 'image', 'genre']
        
        
class ContributionForm(forms.ModelForm):
    class Meta:
        model = Contribution
        fields = ['text']

EntregaFinalCoder/myproject/accounts/views.py

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.shortcuts import get_object_or_404
from storywriting.forms import StoryForm
from django.apps import apps

Story = apps.get_model('storywriting', 'Story')


class CustomLoginView(auth_views.LoginView):
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

def login_redirect(request):
    return redirect('login')

def home(request):
    return render(request, 'home.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

@login_required
def profile(request):
    user_stories = Story.objects.filter(user=request.user)
    return render(request, 'accounts/profile.html', {'stories': user_stories})

@login_required
def edit_story(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    if request.method == 'POST':
        form = StoryForm(request.POST, request.FILES, instance=story)
        if form.is_valid():
            form.save()
            # messages.success(request, 'Story updated successfully')
            return redirect('profile')
    else:
        form = StoryForm(instance=story)
    return render(request, 'accounts/edit_story.html', {'form': form})

@login_required
def delete_story(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    if request.user == story.user:
        story.delete()
        # messages.success(request, 'Story deleted successfully')
    return redirect('profile')



@login_required(login_url='login_redirect')
def create_story(request):
    return render(request, 'accounts/create_story.html')


EntregaFinalCoder/myproject/myproject/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

EntregaFinalCoder/myproject/storywriting/views.py
from django.shortcuts import render, redirect
from .forms import StoryForm
from .models import Story
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from .models import Story, Contribution
from .forms import ContributionForm
from django.db.models import Q

# Función para crear una historia
# Crea un form para crear una historia, y si es válido, se guarda y te redirige a la página de leer historias
@login_required
def create_story(request):
    if request.method == 'POST':
        form = StoryForm(request.POST, request.FILES)
        if form.is_valid():
            story = form.save(commit=False)
            story.user = request.user
            story.save()
            # messages.success(request, 'You have successfully created a story.')
            return redirect('read_stories')
    else:
        form = StoryForm()
    context = {'form': form}
    return render(request, 'storywriting/create_story.html', context)


# Función para leer historias
# Obtiene todas las historias y las ordena por fecha de creación
def read_stories(request):
    stories = Story.objects.all().order_by('-created_at')
    context = {'stories': stories}
    return render(request, 'storywriting/read_stories.html', context)


# Función para editar una historia
# Obtiene la historia que se quiere editar y si el usuario es el creador de la historia, se edita
@login_required(login_url='login_redirect')
def join_story(request, story_id):
    story = get_object_or_404(Story, pk=story_id)
    if request.method == 'POST':
        form = ContributionForm(request.POST)
        if form.is_valid():
            contribution = form.save(commit=False)
            contribution.story = story
            contribution.user = request.user
            contribution.save()
            # Actualiza el cuerpo de la historia con la contribución
            story.body += "\n" + contribution.text
            story.save()
            return redirect('story_detail', story_id=story.id)
    else:
        form = ContributionForm()
    return render(request, 'storywriting/join_story.html', {'story': story, 'form': form})

# Función para editar una historia
# Obtiene la historia que se quiere editar y si el usuario es el creador de la historia le permite editar el original
def story_detail(request, story_id):
    story = get_object_or_404(Story, pk=story_id)
    return render(request, 'storywriting/story_detail.html', {'story': story})

# Función para retornar todas las historias de la database y filtrarlas por título, usuario o género
def browse_stories(request):
    stories = Story.objects.all()
    return render(request, 'storywriting/browse_stories.html', {'stories': stories})


def browse_stories(request):
    query = request.GET.get('q')
    if query:
        stories = Story.objects.filter(
            Q(title__icontains=query) |
            Q(user__username__icontains=query) |  
            Q(genre__icontains=query)
        )
    else:
        stories = Story.objects.all()

    return render(request, 'storywriting/browse_stories.html', {'stories': stories})

EntregaFinalCoder/myproject/accounts/templates/accounts/edit_story.html
{% extends 'base.html' %}

{% block content %}
<h2>Edit Story</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
</form>
{% endblock %}

EntregaFinalCoder/myproject/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h2>Login</h2>
{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}
<form method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username">
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">
    <button type="submit">Log in</button>
</form>
{% endblock %}

EntregaFinalCoder/myproject/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'styles.css' %}">

<h2>Profile</h2>
<p>Welcome, {{ user.username }}!</p>

{% for story in stories %}
    <div class="card">
        <div class="image-container">
            <img src="{{ story.image.url }}" alt="{{ story.title }}">
        </div>
        <div class="text-container"> 

            <div class="story-details">
                

                
                <p class="author">Author | {{ story.user.username }}</p>
                <p class="title">Title | {{ story.title }}</p>
                <p class="genre">Genre | {{ story.genre }}</p>
                <p class="date">Date | {{ story.created_at|date:"F d, Y" }}</p>

            </div>
            <div class="story-excerpt">
                <p>{{ story.body }}</p>
            </div>
            <button class="story-button edit-button">
                <a href="{% url 'edit_story' story.id %}">Edit</a>
            </button>
            <button class="story-button delete-button">
                <a href="{% url 'delete_story' story.id %}">Delete</a>
            </button>

        </div>
        
    </div>
{% endfor %}

{% endblock %}

EntregaFinalCoder/myproject/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Signup</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}

EntregaFinalCoder/myproject/myproject/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About Me / Agustin Garagorry Guerra</h1>
    <p>My name is Agustín Garagorry, and I am a former member of the research team at the University of Turku, focusing on the implementation of Generative AI in educational environments (<a href="https://www.mdpi.com/2071-1050/15/18/14025">Check the latest paper</a>)My background as a UX/UI designer has enabled me to bring creative solutions to complex problems, designing innovative frameworks that address various challenges. My goal is to foster international collaborations that enhance the quality of life for as many children as possible.
        <br>
        Throughout my career, I have gained extensive experience in managing and leading teams towards successful outcomes. I have balanced client expectations with team capabilities and timelines, ensuring comfort and satisfaction for all stakeholders.
        <br>
        I consider myself a versatile individual who quickly learns new skills and understands how to apply them to enhance team performance.
        <br>
        Originally from Uruguay, I am now living in Finland—a surprising and exciting destination for me. I am a lover of dogs and enjoy spending my evenings with a good cup of coffee.</p>

    <h2>Why I Created This Website</h2>
    <p>For my final project at Coderhouse, I have envisioned a unique platform that allows collaborative storytelling. This concept is inspired by a classic Uruguayan game, where children weave stories together using small pieces of paper during school hours. The core idea is to create a space where people can write and express themselves in a joint narrative, seamlessly integrating their ideas with those of others.
        <br>
        Imagine the excitement of adapting your story to intertwine with someone else's and the thrill of influencing the direction of a shared narrative. This project aims to recapture the joy of collaborative storytelling, albeit in a modern digital format. Due to time constraints, I had to simplify the project's complexity, but the essence of playful, collective creativity remains intact. Let's see what fascinating stories emerge from this experience!
    </p>
{% endblock %}

EntregaFinalCoder/myproject/myproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Story Site</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myproject/styles.css' %}">
</head>
<body>
    {% block header %}
    <header>
        <!-- Titulo que va a aparecer en la main-->
        <h1>write with me</h1>
        <nav class="nav">|
            <!-- Menú que chequea, si el usuario está o no authentificado, usando una propiedad de django, si está logeado le muestra profile y cerrar sesión, sion, login y sign up -->
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a> |
            <a href="{% url 'profile' %}">Profile</a> |
        {% else %}
            <a href="{% url 'login' %}">Login</a> |
            <a href="{% url 'signup' %}">Sign up</a> |
        {% endif %}
        <!-- Resto del nav no varía si el usuario está o no logeado-->
            <a href="{% url 'about' %}">About Me</a> |
            <a href="{% url 'create_story' %}">Create a New Story</a> |
            <a href="{% url 'browse_stories' %}">Join a New Story</a> |
            <a href="{% url 'read_stories' %}">Read Stories</a> |
            <a href="{% url 'home' %}">Home</a> |       
        </nav>
    </header>
    {% endblock %}
    <main>
        <!-- Esto lo estaba usando para avisarle al usuario si había algo pasando por ejemplo, Ups no estás logeado, estaba teniendo problemas con el views, lo dejo para terminar en algún otro momento, si no hay mensajes no cambia nada  -->
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p style="text-align: center; margin-bottom: 5vh;">&copy; 2023 Write With Me. Entrega Final Coderhouse  |<a href="https://www.linkedin.com/in/agust%C3%ADn-garagorry-786555116/">Agustin Garagorry Linkedin</a>|<a href="#">abgagu@utu.fi</a></p>
    </footer>
</body>
</html>

EntregaFinalCoder/myproject/myproject/templates/home.html
{% extends 'base.html' %}

{% block header %}
<header class="home-header">
    <h1>write with me</h1>
    <!-- En este caso necesitaba que el home fuera más atractivo con el menu en el medio de la pantalla
    opté por darle un id a cada item para personalizarlos en el home -->
    <nav class="nav">|
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" id="Logout">Logout</a> |
        <a href="{% url 'profile' %}" id="Profile">Profile</a> |
    {% else %}
        <a href="{% url 'login' %}" id="Login">Login</a> |
        <a href="{% url 'signup' %}" id="Sign">Sign up</a> |
    {% endif %}
        <a href="{% url 'about' %}" id="About">About Me</a> |
        <a href="{% url 'create_story' %}" id="Create">Create a New Story</a> |
        <a href="{% url 'browse_stories' %}" id="Join">Join a New Story</a> |
        <a href="{% url 'read_stories' %}" id="Read">Read Stories</a> |
        <a href="{% url 'home' %}" id="Home">Home</a> |       
    </nav>
</header>
{% endblock %}

{% block content %}
<p class="mainpagep">create our own story</p>
{% endblock %}

EntregaFinalCoder/myproject/storywriting/templates/storywriting/browse_stories.html
{% extends 'base.html' %}

{% block content %}
<h1>Browse Stories</h1>
<!-- Buscador de historias usando querrys-->
<form method="GET">
    <input type="text" name="q" placeholder="Search for a story/author/gendre...">
    <button type="submit">Search</button> 
</form>
<!-- Despliego de historias, en este caso no llamo las imágenes porque es una versión simplificada del reading -->
{% for story in stories %}
    <div>
        <h2>{{ story.title }}</h2>
        <p>By {{ story.user.username }}</p>
        <p>Genre: {{ story.genre }}</p>
        <p>Posted on {{ story.created_at }}</p>
        <p>{{ story.body }}</p>
        <a href="{% url 'join_story' story.id %}">Join this story</a>
        <hr style="border-top: solid #ffffff; margin-top: 20px;">
    </div>
{% endfor %}

{% endblock %}

EntregaFinalCoder/myproject/storywriting/templates/storywriting/create_story.html
{% extends 'base.html' %}

{% block content %}
<h2>Create your story</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Story</button>
</form>

{% endblock %}

EntregaFinalCoder/myproject/storywriting/templates/storywriting/join_story.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ story.title }}</h2>

<!-- Display the original story text -->
<div class="original-story">
    <h3>Original Story:</h3>
    <p>{{ story.body|linebreaksbr }}</p>
</div>

<!-- Display the contributions to the story -->
{% for contribution in story.contribution_set.all %}
    <p class="{% if contribution.user != story.user %}other-user{% endif %}">
        {{ contribution.text|linebreaksbr }}
    </p>
{% endfor %}

<!-- Form to add to the story -->
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Contribute</button>
</form>

{% endblock %}

EntregaFinalCoder/myproject/storywriting/templates/storywriting/read_stories.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'styles.css' %}">

<h2>Take some time to read some cool stories</h2>

{% for story in stories %}
    <div class="card">
        <div class="image-container">
            <img src="{{ story.image.url }}" alt="{{ story.title }}">
        </div>
        <div class="text-container">
            <div class="story-details">
                
                <h2 class="title">Title | {{ story.title }}</h2>
                <p class="author">Author | {{ story.user.username }}</p>
                <p class="genre">Genre | {{ story.genre }}</p>
                <p class="date">Date | {{ story.created_at|date:"F d, Y" }}</p>

            </div>
            <div class="story-excerpt">
                <p>{{ story.body|linebreaksbr }}</p>
                {% for contribution in story.contribution_set.all %}
                    <p class="{% if contribution.user != story.user %}other-user{% endif %}">
                        {{ contribution.text|linebreaksbr }}
                    </p>
                {% endfor %}
                <hr style="border-top: solid #ffffff; margin-top: 20px;">

            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}

EntregaFinalCoder/myproject/storywriting/templates/storywriting/story_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ story.title }}</h2>
{% for contribution in story.contribution_set.all %}
    <p class="{% if contribution.user != story.user %}other-user{% endif %}">
        {{ contribution.text }}
    </p>
{% endfor %}
{% endblock %}